### ISSUE TITLE
Extension doesn't work in sync with clipboard insert extensions

### ISSUE THREAD

**Issue by Rusiann** [rjpeterson/Hanzisize#67]
Text copied from clipboard are pasted on html page but extension doesn't work.

**Comment by rjpeterson** [comment]
Do you mean a page that is loaded locally from your hard drive? Or pasted into a form field? Can you give me a website to try so that I can see what you mean?

**Comment by Rusiann** [comment]
[Vertical Text HTML.zip](https://github.com/rjpeterson/Hanzisize/files/5258674/Vertical.Text.HTML.zip)
I uploaded the html file as zip. You have to use a clipboard inserter extension to paste text from somewhere into browser.

**Comment by rjpeterson** [comment]
This seems like an incredibly specific problem that requires a second, also not widely used extension to also be installed and in use. There is no way I can guarantee Hanzisize will work smoothly with all other extensions. Unless you can provide a compelling reason why Hanzisize needs to work in sync with your clipboard insert extension, I probably wont attempt to fix this.

**Comment by Rusiann** [comment]
Looks like I missed the point. Clipboard inserter only pastes the text into blank html file. The two extension do not have to work in sync. To prove this, I opened a html with text from my hard drive but the extension won't load at all. So the problem might lie on htmls.

**Comment by rjpeterson** [comment]
Please download the file Hanzisize/src/test/testpage.html, open it in a web browser, and try to use Hanzisize. Does it work?

**Comment by Rusiann** [comment]
No. The extension is still stuck at loading.

**Comment by rjpeterson** [comment]
Please supply the following information: 
1.Operating system
2.web browser & version number
3.other installed extensions
4.steps to reproduce the problem you are having

**Comment by Rusiann** [comment]
1.Windows 10
2.Microsoft Edge 85.0.564.51
3.These may be unrelated, but here are Adblock, kaspersky
4. First use  Hanzisize/src/test/testpage.html to check the extension if it works.
   Then use  https://chrome.google.com/webstore/detail/clipboard-inserter/deahejllghicakhplliloeheabddjajm to install clipboard extension.
[New Text Document.txt](https://github.com/rjpeterson/Hanzisize/files/5269316/New.Text.Document.txt) Use this sample text to copy after activating the former extension at a blank html page. You just have to copy the text. Then it will automatically show on blank html. Then use Hanzisize to check if it works.
The two steps only imply the problem of this extension unaffected by others not working, I think.

**Comment by rjpeterson** [comment]
Hanzisize is not currently compatible with Microsoft Edge. It is on the roadmap, but at the moment the only supported browsers are Google Chrome and Mozilla Firefox.

**Comment by rjpeterson** [comment]
see issue #25 for update on browser compatibility.
